"""Adiciona tabela de professores

Revision ID: 29eadde945c8
Revises: 5f6d867b8401
Create Date: 2025-09-25 14:02:20.678309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29eadde945c8'
down_revision: Union[str, Sequence[str], None] = '5f6d867b8401'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alunos_ano'), table_name='alunos')
    op.drop_index(op.f('ix_alunos_id'), table_name='alunos')
    op.drop_table('alunos')
    op.drop_index(op.f('ix_escolas_ano'), table_name='escolas')
    op.drop_index(op.f('ix_escolas_id'), table_name='escolas')
    op.drop_index(op.f('ix_escolas_nome'), table_name='escolas')
    op.drop_table('escolas')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('escolas',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('escolas_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('nome', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('regiao', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('pontuacao_premio', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('ideb_publico', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('ano', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='escolas_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('ix_escolas_nome'), 'escolas', ['nome'], unique=False)
    op.create_index(op.f('ix_escolas_id'), 'escolas', ['id'], unique=False)
    op.create_index(op.f('ix_escolas_ano'), 'escolas', ['ano'], unique=False)
    op.create_table('alunos',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome_anonimizado', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('nota_geral', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('escola_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ano', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['escola_id'], ['escolas.id'], name=op.f('alunos_escola_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('alunos_pkey'))
    )
    op.create_index(op.f('ix_alunos_id'), 'alunos', ['id'], unique=False)
    op.create_index(op.f('ix_alunos_ano'), 'alunos', ['ano'], unique=False)
    # ### end Alembic commands ###
