"""Finaliza estrutura de escolas, alunos e professores

Revision ID: 316ebf250d63
Revises: 29eadde945c8
Create Date: 2025-09-25 14:35:48.194905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '316ebf250d63'
down_revision: Union[str, Sequence[str], None] = '29eadde945c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
