"""create tables escolas/alunos/professores

Revision ID: 7be21e7d0167
Revises: 6c4c0cfb9a31
Create Date: 2025-09-25 18:04:55.021673

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# Adicionado para garantir que os modelos sejam reconhecidos pelo autogenerate
from app.db.base import Base
from app.db import models


# revision identifiers, used by Alembic.
revision: str = '7be21e7d0167'
down_revision: Union[str, Sequence[str], None] = '6c4c0cfb9a31'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###