"""Cria schema inicial completo

Revision ID: 8f40356be98a
Revises: 
Create Date: 2025-09-25 16:06:46.342813

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# Adicionado para garantir que os modelos sejam reconhecidos pelo autogenerate
from app.db.base import Base
from app.db import models


# revision identifiers, used by Alembic.
revision: str = '8f40356be98a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###