"""Cria tabelas iniciais para escolas e alunos

Revision ID: c71d90e0cc98
Revises: 
Create Date: 2025-09-11 15:51:55.016567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c71d90e0cc98'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('escolas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('regiao', sa.String(), nullable=True),
    sa.Column('pontuacao_premio', sa.Float(), nullable=True),
    sa.Column('ideb_publico', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_escolas_id'), 'escolas', ['id'], unique=False)
    op.create_index(op.f('ix_escolas_nome'), 'escolas', ['nome'], unique=False)
    op.create_table('alunos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_anonimizado', sa.String(), nullable=True),
    sa.Column('nota_geral', sa.Float(), nullable=True),
    sa.Column('escola_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['escola_id'], ['escolas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alunos_id'), 'alunos', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alunos_id'), table_name='alunos')
    op.drop_table('alunos')
    op.drop_index(op.f('ix_escolas_nome'), table_name='escolas')
    op.drop_index(op.f('ix_escolas_id'), table_name='escolas')
    op.drop_table('escolas')
    # ### end Alembic commands ###
