"""Adiciona campo ano nos modelos

Revision ID: d17ef2541d08
Revises: c71d90e0cc98
Create Date: 2025-09-11 16:52:49.697766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd17ef2541d08'
down_revision: Union[str, Sequence[str], None] = 'c71d90e0cc98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alunos', sa.Column('ano', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_alunos_ano'), 'alunos', ['ano'], unique=False)
    op.add_column('escolas', sa.Column('ano', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_escolas_ano'), 'escolas', ['ano'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_escolas_ano'), table_name='escolas')
    op.drop_column('escolas', 'ano')
    op.drop_index(op.f('ix_alunos_ano'), table_name='alunos')
    op.drop_column('alunos', 'ano')
    # ### end Alembic commands ###
